config/routes.rb
Rails.application.routes.draw do
  get 'new', to: 'games#new', as: :new
  post 'score', to: 'games#score', as: :score
  get 'reset_session', to: 'games#reset_session', as: :reset
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController
  def new
    @grid = Array.new(10) { ('A'..'Z').to_a.sample }
  end

  def score
    @userinput = params[:input]
    @grid = params[:grid]
    session[:score] = session[:score] || 0

    if included?(@userinput.upcase, @grid)
      if english_word?(@userinput)
        @output = "Congratulations! #{@userinput.upcase} is a valid English word!"
        session[:score] += compute_score(@userinput)

      else
        @output = "Sorry but #{@userinput.upcase} does not seem to be a valid English word!"
      end
    else
      @output = "Sorry but #{@userinput.upcase} cannot be built out of #{@grid}"
    end
    @score = session[:score]
    # The word cant be built out of the original grid
    # The word is valid according to the grid, but is not a valid English word
    # The word is valid according to the grid and is an English word
  end

  def reset_session
    session[:score] = 0
    redirect_to new_path
  end

  private

  def english_word?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    json['found']
  end

  def included?(guess, grid)
    guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt)
    attempt.size * 2.0
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>

<div>
<% @grid.each do |letter| %>
  <li> <%= letter %> </li>
<% end %>
</div>

<form action="/score" method="post">
  <p> What is the longest word you can find? </p>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :grid, @grid %>
  <input type="text" name="input" placeholder="Your Word">
  <input type="submit" value = "Play!">
</form>

app/views/games/score.html.erb
<h1>Your Score</h1>
<div>
  <%= @output %>
  <br>
  <%= @score %>
</div>

<p><%= link_to "End Session", reset_path %></p>

<p><%= link_to "Play Again", new_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>